# Generated by Django 3.2.5 on 2021-08-02 16:06

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Информация о себе')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения: dd/mm.YYYY')),
                ('avatar', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/', verbose_name='Аватар')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Модератор')),
                ('is_moderator', models.BooleanField(default=False, verbose_name='Модератор')),
                ('company', models.ForeignKey(on_delete=models.SET(accounts.models.get_stab_company_id), related_name='employee', to='companies.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
