# Generated by Django 3.2.5 on 2021-08-02 06:23

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20210802_0923'),
        ('accounts', '0005_alter_profile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(on_delete=models.SET(accounts.models.get_stab_company_id), related_name='employee', to='companies.company'),
        ),
    ]
