# Generated by Django 3.2.5 on 2021-07-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='foundation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='age',
            field=models.IntegerField(),
        ),
    ]
