# Generated by Django 3.2.5 on 2021-08-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Информация о компании')),
                ('news', models.TextField(blank=True, verbose_name='Новости компании')),
                ('foundation_date', models.DateField(blank=True, null=True, verbose_name='Дата основания: YYYY-mm-dd')),
                ('avatar', models.ImageField(blank=True, upload_to='company/%Y/%m/%d/', verbose_name='Аватар')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
