# Generated by Django 3.2.5 on 2021-07-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='company/%Y/%m/%d/', verbose_name='Аватар'),
        ),
    ]
