# Generated by Django 3.2.5 on 2021-08-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20210728_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='news',
            field=models.TextField(blank=True, verbose_name='Новости компании'),
        ),
    ]
