# Generated by Django 3.2.5 on 2021-08-02 06:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0003_auto_20210802_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='company_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
